apiVersion: v1
kind: Service
metadata:
  name: spring-svc
  namespace: test-ns
spec:
  selector:
    app: spring-application  # Make sure this matches your pod/deployment label
  type: NodePort
  ports:
    - port: 9090          # Service port
      targetPort: 8080    # Container port
      nodePort: 30090     # Node port exposed on EC2 (must be 30000–32767)
